/**
    Use this file to implement business logic. This file will be preserved
    during next compilations.

    Generated by: silvera
    Date: 2020-10-17 12:42:52
*/

package com.silvera.Bookstore.service.impl;

import java.util.Optional;
import org.springframework.stereotype.Service;
import com.silvera.Bookstore.domain.model.*;
import com.silvera.Bookstore.repository.*;
import com.silvera.Bookstore.service.base.*;

import org.springframework.beans.factory.annotation.Autowired;





@Service
public class BookstoreService implements IBookstoreService {





    @Autowired
    BookRepository bookRepository;


    public BookstoreService(){
        super();
    }

    // Auto-generated CRUD methods


    @Override
    public Book createBook(Book book){
        bookRepository.save(book);
        Optional<Book> opt = bookRepository.findById(book.getId());
        return opt.orElse(null);
    }

    @Override
    public Book updateBook(java.lang.String id, Book bookUpdate){
        Book entity = this.readBook(id);
        bookRepository.save(bookUpdate);
        return bookUpdate;
    }

    @Override
    public Book readBook(java.lang.String id){
        Optional<Book> opt = bookRepository.findById(id);
        return opt.orElseThrow(IllegalArgumentException::new);
    }

    @Override
    public void deleteBook(java.lang.String id){
        Book entity = readBook(id);
        bookRepository.delete(entity);
    }





    @Override
    public java.util.List<Book> listBooks() {
        return bookRepository.findAll();
    }



    @Override
    public java.lang.Boolean bookExists(java.lang.String isbn) {
        Optional<Book> opt = bookRepository.findById(isbn);
        return opt.isPresent();
    }



    @Override
    public java.lang.Double bookPrice(java.lang.String isbn) {
        Book book = readBook(isbn);
        return book.getPrice();
    }


}