/**
    Use this file to implement business logic. This file will be preserved
    during next compilations.

    Generated by: silvera
    Date: 2020-10-18 13:54:58
*/

package com.silvera.EmailNotifier.service.impl;

import java.util.Optional;
import org.springframework.stereotype.Service;
import com.silvera.EmailNotifier.domain.model.*;
import com.silvera.EmailNotifier.service.base.*;
import com.silvera.EmailNotifier.repository.*;
import com.silvera.EmailNotifier.messages.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.kafka.core.KafkaTemplate;


@Service
public class EmailNotifierService implements IEmailNotifierService {




    @Autowired
    NotificationRepository notificationRepo;

    // Auto-generated CRUD methods




    @Override
    public java.util.List<Notification> listNotifications(){
       return notificationRepo.findAll();
    }




    @Override
    public void orderCreated(com.silvera.EmailNotifier.messages.ordermsggroup.OrderCreated message){
        Notification n = new Notification();
        n.setOrderId(message.getOrderId());
        n.setUserEmail(message.getUserEmail());

        notificationRepo.save(n);

        System.out.println("OrderCreated!");
    }



    @Override
    public void orderUpdated(com.silvera.EmailNotifier.messages.ordermsggroup.OrderUpdated message){
        Notification n = new Notification();
        n.setOrderId(message.getOrderId());
        n.setUserEmail(message.getUserEmail());

        notificationRepo.save(n);

        System.out.println("OrderUpdated!");
    }



    @Override
    public void orderDeleted(com.silvera.EmailNotifier.messages.ordermsggroup.OrderDeleted message){
        Notification n = new Notification();
        n.setOrderId(message.getOrderId());
        n.setUserEmail(message.getUserEmail());

        notificationRepo.save(n);

        System.out.println("Order Deleted!");
    }



}